# Generated by Django 5.2.8 on 2025-11-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Credito",
            fields=[
                (
                    "proyecto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="activo.proyecto",
                    ),
                ),
                ("cupo_total", models.DecimalField(decimal_places=2, max_digits=15)),
                ("porcentaje_max_desembolso", models.FloatField()),
                ("periodo_inicial", models.PositiveIntegerField()),
                ("periodo_final", models.PositiveIntegerField()),
                ("tasa_interes_anual", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Subetapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activo.proyecto",
                    ),
                ),
            ],
            options={
                "unique_together": {("proyecto", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="MovimientoFinanciero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=15)),
                ("periodo", models.PositiveIntegerField()),
                ("concepto", models.CharField(max_length=10)),
                (
                    "subetapa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activo.subetapa",
                    ),
                ),
            ],
        ),
    ]
